config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/about', to: "pages#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
end

app/models/tag.rb
class Tag < ApplicationRecord
  enum status: [ :active, :archived, :other] # 0, 1, 2
  has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  belongs_to :tag
end
# name description important done

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def hello
    render plain: "Hello World"
  end

  def home
    @msg = "Hello World?"
  end

  def about

  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def new
    @todo = Todo.new
  end

  #POST
  def create
    @todo = Todo.new(todo_params)
    @todo.done = false
    if @todo.save
      flash[:msg] = "TODOs nr. #{@todo.id} created successfully"
      redirect_to todo_path(@todo) #show
    else
      flash[:msg] = @todo.errors.full_messages[0]
      render 'new'
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  #GET
  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      flash[:msg] = "TODOs nr. #{@todo.id} edited successfully"
      redirect_to action: "index"
    else
      flash[:msg] = @todo.errors.full_messages[0]
      render 'edit'
    end
  end

  def index
    @todos = Todo.all
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:msg] = "TODOs nr. #{@todo.id} DELETED"
    redirect_to action: "index"
  end

  private
  def todo_params
    params.require(:todo).permit(:name, :description, :important, :done)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <%= value %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2><%= @msg %></h2>

app/views/todos/edit.html.erb
<h2>Edit a TODO</h2>

<% if @todo.errors.any? %>
<% @todo.errors.full_messages.each do |m| %>
<%= m %>
<% end %>
<% end %>
<%= form_with model: @todo do |form| %>
<p>
    <%= form.label :name %>
    <%= form.text_field :name %>
</p>
<p>
    <%= form.label :descriptions %>
    <%= form.text_area :description, size: "60x5" %>
</p>
<p>
    <%= form.label :important %>
    <%= form.check_box :important %>
</p>
  <p>
    <%= form.label :done %>
    <%= form.check_box :done %>
  </p>


  <%= form.submit %>
<% end %>

app/views/todos/index.html.erb
<h2>All  unfinished TODO's are here:</h2>

<ul>
  <% @todos.each do |t| %>
  <li>
    <% unless t.done %>
      <%=t.id %>
      <%= link_to t.name, edit_todo_path(t) %>
      <em property="italic">Is Important? </em>
      <%=t.important %>
    <% end %>
  </li>
  <% end %>
</ul>

<h2>Finished TODO`s go here:</h2>

<ul>
  <% @todos.each do |t| %>
      <% if t.done %>
      <li>
        <%= link_to t.name, todo_path(t) %>
        <%=t.important %>
      </li>
      <% end %>
  <% end %>
</ul>

<p>
  <%= link_to "Add new TODO", new_todo_path %>
</p>

app/views/todos/new.html.erb
<h2>Create a new TODO</h2>

<% if @todo.errors.any? %>
  <% @todo.errors.full_messages.each do |m| %>
    <%= m %>
  <% end %>
<% end %>
<%= form_with model: @todo do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :descriptions %>
    <%= form.text_area :description, size: "60x5" %>
  </p>
  <p>
    <%= form.label :important %>
    <%= form.check_box :important %>
  </p>

  <%= form.submit %>
<% end %>

app/views/todos/show.html.erb
<ul>
<p>
  <li>
    <strong><%= @todo.name %></strong>
  </li>
</p>
  <p>
  <li>
    <%= @todo.description %>
  </li>
  </p>
  <p>
  <li>
    <%= @todo.important %>
  </li>
  </p>
  <p>
  <li>
    <%= @todo.done %>
  </li>
  </p>
</ul>

<%= link_to "Back to Index Page", todos_path %> | <%= link_to "Delete TODO", todo_path(@todo), method: "delete",
                                                              data: { confirm: "Are you sure?"} %>